# Generated by Django 6.0.3 on 2026-04-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kaspi_url',
            field=models.URLField(blank=True, null=True, verbose_name='Kaspi ссылка'),
        ),
    ]
